- name: Atualizar o sistema ORACLE YUM
  yum:
    name: '*'
    state: latest
  become: yes

- name: Instalar o dnf (se necessário)
  yum:
    name: dnf
    state: present
  become: yes


- name: Atualizar o sistema ORACLE DNF
  ignore_errors: yes
  shell: dnf update -y
  
- name: Atualizar todos os pacotes
  ignore_errors: yes
  dnf:
    name: '*'
    state: latest


- name: Baixar o EPEL Release
  get_url:
    url: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    dest: /tmp/epel-release-latest-7.noarch.rpm

- name: Instalar o EPEL Release
  yum:
    name: /tmp/epel-release-latest-7.noarch.rpm
    state: present

- name: Instalar serviços
  ignore_errors: yes
  dnf:
    name: "{{ servicos_oracle }}"
    state: present

- name: Adicionar repositório Zabbix
  yum:
    name: https://repo.zabbix.com/zabbix/6.0/rhel/7/x86_64/zabbix-release-6.0-4.el7.noarch.rpm
    state: present

- name: Instalar Zabbix Agent
  ansible.builtin.yum:
    name: zabbix-agent
    state: present

- name: Habilitar e iniciar o serviço Zabbix Agent
  ansible.builtin.systemd:
    name: zabbix-agent
    enabled: yes


- name: "Configurar fuso horário para São Paulo"
  timezone:
    name: America/Sao_Paulo

- name: Remover o Podman
  yum:
    name: podman
    state: absent

- name: Instalar Docker
  dnf:
    name: docker
    state: present
  become: yes

- name: Iniciar e habilitar o serviço Docker
  systemd:
    name: docker
    state: started
    enabled: yes
  become: yes

- name: Adicionar o usuário ao grupo docker
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes
  become: yes

- name: Instalar Docker Compose
  get_url:
    url: "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)"
    dest: /usr/local/bin/docker-compose
    mode: 'u+x'
  become: yes

- name: Verificar a instalação do Docker Compose
  command: docker-compose --version
  register: docker_compose_version
  failed_when: docker_compose_version.rc != 0
  become: yes